import { AgentProfile, Deal, Intent, Listing, NegotiationEvent } from "@/types/domain";

const now = new Date().toISOString();

export const seedIntents: Intent[] = [
  {
    id: "intent-macbook",
    user_id: "user-demo",
    item: "MacBook Pro 14-inch M3",
    location: "San Francisco",
    max_price: 1850,
    urgency: "medium",
    flexibility: 12,
    agent_permissions: {
      canNegotiate: true,
      canIncreaseOffer: true,
      canCloseInstantly: false,
    },
    status: "active",
    created_at: now,
  },
  {
    id: "intent-sofa",
    user_id: "user-demo",
    item: "Cloud couch sectional",
    location: "Los Angeles",
    max_price: 900,
    urgency: "low",
    flexibility: 18,
    agent_permissions: {
      canNegotiate: true,
      canIncreaseOffer: true,
      canCloseInstantly: false,
    },
    status: "active",
    created_at: now,
  },
  {
    id: "intent-bike",
    user_id: "user-demo",
    item: "Specialized road bike",
    location: "New York",
    max_price: 2200,
    urgency: "high",
    flexibility: 8,
    agent_permissions: {
      canNegotiate: true,
      canIncreaseOffer: true,
      canCloseInstantly: true,
    },
    status: "active",
    created_at: now,
  },
];

export const seedListings: Listing[] = [
  {
    id: "listing-1",
    title: "MacBook Pro 14 M3, 18GB RAM, mint",
    price: 2095,
    location: "San Francisco",
    age_of_listing: 9,
    seller_id: "seller-neo",
    listing_url: "https://example.com/listings/macbook-pro-14",
    competition: 0.44,
    category: "laptops",
  },
  {
    id: "listing-2",
    title: "MacBook Pro 14-inch M3, silver",
    price: 1940,
    location: "San Francisco",
    age_of_listing: 17,
    seller_id: "seller-orbit",
    listing_url: "https://example.com/listings/macbook-pro-14-silver",
    competition: 0.38,
    category: "laptops",
  },
  {
    id: "listing-3",
    title: "Restoration Hardware style cloud sectional",
    price: 1150,
    location: "Los Angeles",
    age_of_listing: 26,
    seller_id: "seller-marina",
    listing_url: "https://example.com/listings/cloud-sectional",
    competition: 0.21,
    category: "furniture",
  },
  {
    id: "listing-4",
    title: "White modular sofa, delivery available",
    price: 980,
    location: "Los Angeles",
    age_of_listing: 13,
    seller_id: "seller-casa",
    listing_url: "https://example.com/listings/modular-sofa",
    competition: 0.28,
    category: "furniture",
  },
  {
    id: "listing-5",
    title: "Specialized Tarmac SL7 road bike",
    price: 2450,
    location: "New York",
    age_of_listing: 11,
    seller_id: "seller-race",
    listing_url: "https://example.com/listings/tarmac-sl7",
    competition: 0.52,
    category: "bikes",
  },
  {
    id: "listing-6",
    title: "Specialized carbon road bike, race build",
    price: 2310,
    location: "New York",
    age_of_listing: 19,
    seller_id: "seller-sprint",
    listing_url: "https://example.com/listings/carbon-road-bike",
    competition: 0.34,
    category: "bikes",
  },
];

export const seedAgents: AgentProfile[] = [
  {
    intent_id: "intent-macbook",
    negotiation_strategy: "balanced",
    price_curve: "steady",
    timing_interval: 4,
    max_actions_per_day: 18,
    actions_taken_today: 2,
  },
  {
    intent_id: "intent-sofa",
    negotiation_strategy: "conservative",
    price_curve: "start_low",
    timing_interval: 6,
    max_actions_per_day: 12,
    actions_taken_today: 1,
  },
  {
    intent_id: "intent-bike",
    negotiation_strategy: "aggressive",
    price_curve: "urgent",
    timing_interval: 3,
    max_actions_per_day: 24,
    actions_taken_today: 3,
  },
];

export const seedDeals: Deal[] = [
  {
    id: "deal-macbook-1",
    intent_id: "intent-macbook",
    listing_id: "listing-2",
    current_offer: 1775,
    status: "close_to_accept",
    savings_amount: 165,
    transaction_fee: 0,
    created_at: now,
    updated_at: now,
    offers_sent: 2,
    counters_received: 1,
    acceptance_probability: 0.72,
    last_message: "Seller signaled willingness to close if execution happens today.",
  },
];

export const seedEvents: NegotiationEvent[] = [
  {
    id: "event-1",
    deal_id: "deal-macbook-1",
    type: "offer",
    actor: "agent",
    amount: 1710,
    message: "I can settle today at $1,710 with immediate pickup.",
    created_at: now,
  },
  {
    id: "event-2",
    deal_id: "deal-macbook-1",
    type: "counter",
    actor: "seller",
    amount: 1815,
    message: "I can do $1,815 if you close before tonight.",
    created_at: now,
  },
];
